#!/bin/bash
echo "Copy build file"

cd /root/cxlb_toolchain_build/gr-ephyl/build
make install
cp /usr/local/lib/python2.7/dist-packages/ephyl/bs_scheduler.py /cortexlab/toolchains/current/lib/python2.7/dist-packages/ephyl/bs_scheduler.py
cp /usr/local/lib/python2.7/dist-packages/ephyl/sn_scheduler.py /cortexlab/toolchains/current/lib/python2.7/dist-packages/ephyl/sn_scheduler.py
cp /usr/local/lib/python2.7/dist-packages/ephyl/msg_mux.py /cortexlab/toolchains/current/lib/python2.7/dist-packages/ephyl/msg_mux.py
cp /usr/local/lib/python2.7/dist-packages/ephyl/access_control.py /cortexlab/toolchains/current/lib/python2.7/dist-packages/ephyl/access_control.py
cp /usr/local/lib/python2.7/dist-packages/ephyl/easy_upper.py /cortexlab/toolchains/current/lib/python2.7/dist-packages/ephyl/easy_upper.py

